const List<Map<String, String>> allProducts = [
  {
    'id': '1',
    'title': 'Bangles Set',
    'subtitle': 'Gold',
    'price': '₹120.00',
    'imagePath': 'assets/images/product1.png',
    'category': 'Bracelets',
    'gender': 'Womens',
  },
  {
    'id': '2',
    'title': 'Wedding Set',
    'subtitle': 'Gold',
    'price': '₹369.00',
    'imagePath': 'assets/images/product5.png',
    'category': 'Wedding Sets',
    'gender': 'Womens',
  },
  {
    'id': '3',
    'title': 'Diamond Ring',
    'subtitle': 'Diamond and Gold',
    'price': '₹369.00',
    'imagePath': 'assets/images/product3.png',
    'category': 'Rings',
    'gender': 'Unisex',
  },
  {
    'id': '4',
    'title': 'Necklace Set',
    'subtitle': 'Gold',
    'price': '₹369.00',
    'imagePath': 'assets/images/product2.png',
    'category': 'Necklaces',
    'gender': 'Womens',
  },
  {
    'id': '5',
    'title': 'Gold Earrings',
    'subtitle': 'Gold',
    'price': '₹89.00',
    'imagePath': 'assets/images/earring.png',
    'category': 'Earrings',
    'gender': 'Womens',
  },
  {
    'id': '6',
    'title': 'Gold Bracelet',
    'subtitle': 'Gold',
    'price': '₹149.00',
    'imagePath': 'assets/images/bracelet.png',
    'category': 'Bracelets',
    'gender': 'Gents',
  },
  {
    'id': '7',
    'title': 'Gents Gold Ring',
    'subtitle': 'Solid 22k Gold',
    'price': '₹199.00',
    'imagePath': 'assets/images/ring.png',
    'category': 'Rings',
    'gender': 'Gents',
  },
  {
    'id': '8',
    'title': 'Gents Kada Chain',
    'subtitle': 'Classic Gold Link',
    'price': '₹299.00',
    'imagePath': 'assets/images/necklace.png',
    'category': 'Chains',
    'gender': 'Gents',
  },
  {
    'id': '9',
    'title': 'Kids Gold Studs',
    'subtitle': 'Cute Flower Earrings',
    'price': '₹75.00',
    'imagePath': 'assets/images/earring.png',
    'category': 'Earrings',
    'gender': 'Kids',
  },
  {
    'id': '10',
    'title': 'Kids Gold Bracelet',
    'subtitle': 'Adjustable Charm Link',
    'price': '₹95.00',
    'imagePath': 'assets/images/bracelet.png',
    'category': 'Bracelets',
    'gender': 'Kids',
  },
  {
    'id': '11',
    'title': 'Unisex Gold Chain',
    'subtitle': 'Sleek Flat Chain',
    'price': '₹180.00',
    'imagePath': 'assets/images/necklace.png',
    'category': 'Chains',
    'gender': 'Unisex',
  },
];
